### ISSUE TITLE
Testmerge URL is invalid if Github API errors

### ISSUE THREAD

**Issue by FunnyMan3595** [tgstation/tgstation-server#1795]
**Describe the bug**
The URL of a testmerge is set to a non-URL value if the Github API errors out.

**To Reproduce**
1. Have a testmerge.
2. Get an error from Github.
3. Testmerge URL is set to something like "GITHUB API ERROR: RATE LIMITED"

**Expected behavior**
The URL should be valid.  Ideally, it would even go to the matching pull request.

**Additional context**
The line that causes this is here: https://github.com/tgstation/tgstation-server/blob/cde1ea6e1726efe61cd70cff66f7ed08456394c0/src/Tgstation.Server.Host/Components/Repository/GitHubRemoteFeatures.cs#L96 .  Returning any valid URL would be an improvement over the error message, but there's enough information to construct the PR URL without Github's response, so that'd be ideal.

**Comment by Cyberboss** [comment]
The message is intentionally obtuse.

The API errors are because you're accessing the GitHub API without an access token. Setting one, either in the TGS config .yml or the repository settings, will prevent the error from occurring.

If this is on Paradise, I thing @AffectedArc07 may have one set, but it's being used for other things which are causing the rate limit. I'd either clean those up or create a dedicated bot account for TGS.

**Comment by AffectedArc07** [comment]
> The message is intentionally obtuse.
> 
> The API errors are because you're accessing the GitHub API without an access token. Setting one, either in the TGS config .yml or the repository settings, will prevent the error from occurring.
> 
> If this is on Paradise, I thing @AffectedArc07 may have one set, but it's being used for other things which are causing the rate limit. I'd either clean those up or create a dedicated bot account for TGS.

We have one setup, the point of this issue is that a field called `Url` has a high chance of returning things that arent URLs, and given TGS is aware of the repo remote and PR ID from local means, a "fix" for this should be easy enough.
